version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    # This will keep the container running
    command: tail -f /dev/null

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma:/chroma/.chroma/